import { pageRegistry } from '@/lib/cms/page-registry'

export type WebPageCoverageStatus = 'admin' | 'partial' | 'code'

export interface WebPageInventoryEntry {
  route: string
  title: string
  area: string
  source: string
  status: WebPageCoverageStatus
  adminPath?: string
  notes?: string
}

const registryEntries: WebPageInventoryEntry[] = Object.entries(pageRegistry).map(([key, def]) => ({
  route: def.slug,
  title: def.label,
  area: def.slug.startsWith('/help') ? 'Help' : def.slug.startsWith('/blog') ? 'Blog' : 'Marketing',
  source: key === 'blog' ? 'Blog CMS + SEO' : 'CMS Page + SEO',
  status: 'admin',
  adminPath: key === 'blog' ? '/content/blogs' : `/content/pages/${key}`,
  notes: key === 'blog' ? 'Blog list and post metadata are managed in Blogs.' : 'Managed through the page editor and SEO metadata.',
}))

const extraEntries: WebPageInventoryEntry[] = [
  {
    route: '/',
    title: 'Home',
    area: 'Marketing',
    source: 'Code-managed landing page',
    status: 'code',
    notes: 'Homepage structure is still in code. Some shared images and settings come from admin.',
  },
  {
    route: '/all-pages',
    title: 'All Pages',
    area: 'Marketing',
    source: 'Code-managed index page',
    status: 'code',
    notes: 'Reference/index page only. Not currently backed by admin content.',
  },
  {
    route: '/all-services',
    title: 'All Services',
    area: 'Services',
    source: 'Code-managed listing',
    status: 'partial',
    adminPath: '/tasks/categories',
    notes: 'Service catalog data is admin-driven, but this page layout and copy still live in code.',
  },
  {
    route: '/services',
    title: 'Services Landing',
    area: 'Services',
    source: 'Service catalog + web image settings',
    status: 'admin',
    adminPath: '/tasks/categories',
    notes: 'Category content comes from the service catalog. Hero/category imagery comes from admin media settings.',
  },
  {
    route: '/services/[category]',
    title: 'Category Page',
    area: 'Services',
    source: 'Service catalog',
    status: 'admin',
    adminPath: '/tasks/categories',
    notes: 'Route slug, title, description, hero image, visibility, and recurring flags are admin-driven.',
  },
  {
    route: '/services/[category]/[service]',
    title: 'Service Detail Page',
    area: 'Services',
    source: 'Service catalog',
    status: 'admin',
    adminPath: '/tasks/categories',
    notes: 'Long description, benefits, tasks, FAQs, and media are managed in category/service setup.',
  },
  {
    route: '/services/home-repair',
    title: 'Legacy Service Route',
    area: 'Services',
    source: 'Code-managed legacy route',
    status: 'partial',
    adminPath: '/tasks/categories',
    notes: 'Still exists as a legacy route shape. Catalog data is available, but route handling is not fully normalized.',
  },
  {
    route: '/services-by-city',
    title: 'Services by City',
    area: 'Locations',
    source: 'Code-managed listing',
    status: 'code',
    notes: 'Location listing UI is still in code.',
  },
  {
    route: '/locations/[city]',
    title: 'City Landing',
    area: 'Locations',
    source: 'Dynamic service/location route',
    status: 'partial',
    adminPath: '/tasks/categories',
    notes: 'Uses dynamic data, but page-specific location content is not fully managed in admin.',
  },
  {
    route: '/locations/[city]/[service]',
    title: 'City Service Detail',
    area: 'Locations',
    source: 'Dynamic service/location route',
    status: 'partial',
    adminPath: '/tasks/categories',
    notes: 'Service content is admin-driven. City-specific page copy is still limited.',
  },
  {
    route: '/browse-pros',
    title: 'Browse Pros',
    area: 'Marketplace',
    source: 'Code-managed directory page',
    status: 'code',
    notes: 'Operational directory page. Not backed by content admin.',
  },
  {
    route: '/professionals/[id]',
    title: 'Professional Profile',
    area: 'Marketplace',
    source: 'User/profile data',
    status: 'partial',
    adminPath: '/users/profiles',
    notes: 'Driven by live user/profile data, not CMS content.',
  },
  {
    route: '/book-task',
    title: 'Book Task',
    area: 'Booking',
    source: 'Code-managed booking entry',
    status: 'partial',
    adminPath: '/content/page-settings',
    notes: 'Some booking copy comes from Global Settings. Flow structure still lives in code.',
  },
  {
    route: '/task-form',
    title: 'Task Form',
    area: 'Booking',
    source: 'Task questions + code-managed flow',
    status: 'partial',
    adminPath: '/tasks/questions',
    notes: 'Questions are admin-driven. Form UI and some flow copy still live in code.',
  },
  {
    route: '/bookings/[id]',
    title: 'Booking Detail',
    area: 'Booking',
    source: 'Operational booking data',
    status: 'code',
    notes: 'User booking page. Not a CMS surface.',
  },
  {
    route: '/sign-in',
    title: 'Sign In',
    area: 'Auth',
    source: 'Code-managed auth page',
    status: 'code',
    notes: 'Web auth screens are still mostly code-managed.',
  },
  {
    route: '/sign-up',
    title: 'Sign Up',
    area: 'Auth',
    source: 'Code-managed auth page',
    status: 'code',
    notes: 'Web auth screens are still mostly code-managed.',
  },
  {
    route: '/forgot-password',
    title: 'Forgot Password',
    area: 'Auth',
    source: 'Code-managed auth page',
    status: 'code',
    notes: 'Web auth screens are still mostly code-managed.',
  },
  {
    route: '/reset-password',
    title: 'Reset Password',
    area: 'Auth',
    source: 'Code-managed auth page',
    status: 'code',
    notes: 'Web auth screens are still mostly code-managed.',
  },
  {
    route: '/verify-code',
    title: 'Verify Code',
    area: 'Auth',
    source: 'Code-managed auth page',
    status: 'code',
    notes: 'Web auth screens are still mostly code-managed.',
  },
  {
    route: '/welcome',
    title: 'Welcome',
    area: 'Auth',
    source: 'Code-managed auth page',
    status: 'code',
    notes: 'Welcome/auth routing remains in code.',
  },
  {
    route: '/account',
    title: 'Account',
    area: 'Account',
    source: 'Live account data',
    status: 'code',
    notes: 'Application page backed by account data, not CMS.',
  },
  {
    route: '/dashboard',
    title: 'Dashboard',
    area: 'Account',
    source: 'Live user dashboard',
    status: 'code',
    notes: 'Operational/account page, not content-managed.',
  },
  {
    route: '/my-tasks',
    title: 'My Tasks',
    area: 'Account',
    source: 'Live user task data',
    status: 'code',
    notes: 'Operational/account page, not content-managed.',
  },
  {
    route: '/referral',
    title: 'Referral',
    area: 'Referral',
    source: 'Code-managed referral flow',
    status: 'code',
    notes: 'Referral pages are not yet managed in admin.',
  },
  {
    route: '/for-business',
    title: 'For Business',
    area: 'Marketing',
    source: 'CMS Page + SEO',
    status: 'admin',
    adminPath: '/content/pages/for-business',
    notes: 'Public content is now managed in the page editor. Partnership form behavior remains in code.',
  },
  {
    route: '/partner',
    title: 'Partner',
    area: 'Marketing',
    source: 'Redirect alias',
    status: 'partial',
    adminPath: '/content/pages/for-business',
    notes: 'Alias route redirecting to /for-business.',
  },
  {
    route: '/become-tasker',
    title: 'Become Tasker',
    area: 'Marketing',
    source: 'Redirect alias',
    status: 'partial',
    adminPath: '/content/pages/become-100-handy-pro',
    notes: 'Alias route redirecting to /become-100-handy-pro.',
  },
  {
    route: '/become-100-handy-pro',
    title: 'Become 100 Handy Pro',
    area: 'Marketing',
    source: 'CMS Page + SEO',
    status: 'admin',
    adminPath: '/content/pages/become-100-handy-pro',
    notes: 'Public marketing content is now managed in the page editor.',
  },
  {
    route: '/press',
    title: 'Press',
    area: 'Marketing',
    source: 'Code-managed marketing page',
    status: 'code',
    notes: 'Not yet migrated into the CMS.',
  },
  {
    route: '/handycare',
    title: 'Handycare',
    area: 'Marketing',
    source: 'Code-managed marketing page',
    status: 'code',
    notes: 'Not yet migrated into the CMS.',
  },
  {
    route: '/handyman-london',
    title: 'Handyman London',
    area: 'Marketing',
    source: 'Code-managed landing page',
    status: 'code',
    notes: 'SEO landing page still lives in code.',
  },
  {
    route: '/wallpapering-near-me',
    title: 'Wallpapering Near Me',
    area: 'Marketing',
    source: 'Code-managed landing page',
    status: 'code',
    notes: 'SEO landing page still lives in code.',
  },
  {
    route: '/landing-v2',
    title: 'Landing V2',
    area: 'Marketing',
    source: 'Code-managed experiment page',
    status: 'code',
    notes: 'Experimental page, not tied to CMS.',
  },
  {
    route: '/elite-taskers',
    title: 'Elite Taskers',
    area: 'Marketing',
    source: 'Legacy code-managed route',
    status: 'partial',
    adminPath: '/content/pages/elite-taskers',
    notes: 'Legacy route exists alongside the CMS-backed 100 Handy Star page.',
  },
]

export const webPageInventory: WebPageInventoryEntry[] = [...registryEntries, ...extraEntries].sort((a, b) =>
  a.route.localeCompare(b.route)
)
