import { pageRegistry } from '@/lib/cms/page-registry'

export type WebPageCoverageStatus = 'admin' | 'partial' | 'code'

export interface WebPageInventoryEntry {
  route: string
  title: string
  area: string
  source: string
  status: WebPageCoverageStatus
  adminPath?: string
  notes?: string
}

const registryEntries: WebPageInventoryEntry[] = Object.entries(pageRegistry).map(([key, def]) => ({
  route: def.slug,
  title: def.label,
  area: def.slug.startsWith('/help') ? 'Help' : def.slug.startsWith('/blog') ? 'Blog' : 'Marketing',
  source: key === 'blog' ? 'Blog CMS + SEO' : 'CMS Page + SEO',
  status: 'admin',
  adminPath: key === 'blog' ? '/content/blogs' : `/content/pages/${key}`,
  notes: key === 'blog' ? 'Blog list and post metadata are managed in Blogs.' : 'Managed through the page editor and SEO metadata.',
}))

const extraEntries: WebPageInventoryEntry[] = [
  {
    route: '/',
    title: 'Home',
    area: 'Marketing',
    source: 'CMS page + dynamic sections',
    status: 'partial',
    adminPath: '/content/pages/home',
    notes: 'Hero, testimonials, guarantees, and Get Help Today are page-managed. Dynamic category/service sections still read live data and component code.',
  },
  {
    route: '/all-pages',
    title: 'All Pages',
    area: 'Marketing',
    source: 'Code-managed index page',
    status: 'code',
    notes: 'Reference/index page only. Not currently backed by admin content.',
  },
  {
    route: '/all-services',
    title: 'All Services',
    area: 'Services',
    source: 'CMS page + service links',
    status: 'partial',
    adminPath: '/content/pages/all-services',
    notes: 'Hero and link list are page-managed. Links still point into the broader service catalog.',
  },
  {
    route: '/services',
    title: 'Services Landing',
    area: 'Services',
    source: 'Service catalog + web image settings',
    status: 'admin',
    adminPath: '/tasks/categories',
    notes: 'Category content comes from the service catalog. Hero/category imagery comes from admin media settings.',
  },
  {
    route: '/services/[category]',
    title: 'Category Page',
    area: 'Services',
    source: 'Service catalog',
    status: 'admin',
    adminPath: '/tasks/categories',
    notes: 'Route slug, title, description, hero image, visibility, and recurring flags are admin-driven.',
  },
  {
    route: '/services/[category]/[service]',
    title: 'Service Detail Page',
    area: 'Services',
    source: 'Service catalog',
    status: 'admin',
    adminPath: '/tasks/categories',
    notes: 'Long description, benefits, tasks, FAQs, and media are managed in category/service setup.',
  },
  {
    route: '/services/home-repair',
    title: 'Legacy Service Route',
    area: 'Services',
    source: 'Code-managed legacy route',
    status: 'partial',
    adminPath: '/tasks/categories',
    notes: 'Still exists as a legacy route shape. Catalog data is available, but route handling is not fully normalized.',
  },
  {
    route: '/services-by-city',
    title: 'Services by City',
    area: 'Locations',
    source: 'CMS page + static location data',
    status: 'partial',
    adminPath: '/content/pages/services-by-city',
    notes: 'Hero and how-it-works copy are page-managed. City and neighborhood datasets still live in code.',
  },
  {
    route: '/locations/[city]',
    title: 'City Landing',
    area: 'Locations',
    source: 'CMS template + dynamic location data',
    status: 'partial',
    adminPath: '/content/pages/locations-city',
    notes: 'City page templates are admin-managed. City datasets and service availability still come from code and catalog data.',
  },
  {
    route: '/locations/[city]/[service]',
    title: 'City Service Detail',
    area: 'Locations',
    source: 'CMS template + dynamic service data',
    status: 'partial',
    adminPath: '/content/pages/locations-city-service',
    notes: 'Template copy is admin-managed. Service descriptions and icons still rely on catalog and code.',
  },
  {
    route: '/browse-pros',
    title: 'Browse Pros',
    area: 'Marketplace',
    source: 'Code-managed directory page',
    status: 'code',
    notes: 'Operational directory page. Not backed by content admin.',
  },
  {
    route: '/professionals/[id]',
    title: 'Professional Profile',
    area: 'Marketplace',
    source: 'User/profile data',
    status: 'partial',
    adminPath: '/users/profiles',
    notes: 'Driven by live user/profile data, not CMS content.',
  },
  {
    route: '/book-task',
    title: 'Book Task',
    area: 'Booking',
    source: 'Code-managed booking entry',
    status: 'partial',
    adminPath: '/content/page-settings',
    notes: 'Some booking copy comes from Global Settings. Flow structure still lives in code.',
  },
  {
    route: '/task-form',
    title: 'Task Form',
    area: 'Booking',
    source: 'Task questions + code-managed flow',
    status: 'partial',
    adminPath: '/tasks/questions',
    notes: 'Questions are admin-driven. Form UI and some flow copy still live in code.',
  },
  {
    route: '/bookings/[id]',
    title: 'Booking Detail',
    area: 'Booking',
    source: 'Operational booking data',
    status: 'code',
    notes: 'User booking page. Not a CMS surface.',
  },
  {
    route: '/sign-in',
    title: 'Sign In',
    area: 'Auth',
    source: 'CMS copy + auth flow',
    status: 'partial',
    adminPath: '/content/pages/sign-in',
    notes: 'Visible copy and media are managed in Pages. Authentication behavior remains in code.',
  },
  {
    route: '/sign-up',
    title: 'Sign Up',
    area: 'Auth',
    source: 'CMS copy + auth flow',
    status: 'partial',
    adminPath: '/content/pages/sign-up',
    notes: 'Visible copy and media are managed in Pages. Authentication behavior remains in code.',
  },
  {
    route: '/forgot-password',
    title: 'Forgot Password',
    area: 'Auth',
    source: 'CMS copy + auth flow',
    status: 'partial',
    adminPath: '/content/pages/forgot-password',
    notes: 'Visible copy and media are managed in Pages. Password reset behavior remains in code.',
  },
  {
    route: '/reset-password',
    title: 'Reset Password',
    area: 'Auth',
    source: 'CMS copy + auth flow',
    status: 'partial',
    adminPath: '/content/pages/reset-password',
    notes: 'Visible copy and media are managed in Pages. Password reset behavior remains in code.',
  },
  {
    route: '/verify-code',
    title: 'Verify Code',
    area: 'Auth',
    source: 'CMS copy + auth flow',
    status: 'partial',
    adminPath: '/content/pages/verify-code',
    notes: 'Visible copy and media are managed in Pages. Verification logic remains in code.',
  },
  {
    route: '/welcome',
    title: 'Welcome',
    area: 'Auth',
    source: 'CMS copy + auth flow',
    status: 'partial',
    adminPath: '/content/pages/welcome',
    notes: 'Visible copy and background image are managed in Pages. Routing remains in code.',
  },
  {
    route: '/blog/[slug]',
    title: 'Blog Post',
    area: 'Blog',
    source: 'Blog CMS + SEO',
    status: 'admin',
    adminPath: '/content/blogs',
    notes: 'Blog posts, metadata, and routing are managed from Blogs.',
  },
  {
    route: '/help/[article]',
    title: 'Help Article',
    area: 'Help',
    source: 'Help article CMS + SEO',
    status: 'admin',
    adminPath: '/content/help-articles',
    notes: 'Help article content and metadata are managed from Help Articles.',
  },
  {
    route: '/help/account',
    title: 'Help: Account',
    area: 'Help',
    source: 'Help article CMS + SEO',
    status: 'admin',
    adminPath: '/content/help-articles',
    notes: 'Managed through Help Articles.',
  },
  {
    route: '/help/client',
    title: 'Help: Client',
    area: 'Help',
    source: 'Help article CMS + SEO',
    status: 'admin',
    adminPath: '/content/help-articles',
    notes: 'Managed through Help Articles.',
  },
  {
    route: '/help/partnerships',
    title: 'Help: Partnerships',
    area: 'Help',
    source: 'Help article CMS + SEO',
    status: 'admin',
    adminPath: '/content/help-articles',
    notes: 'Managed through Help Articles.',
  },
  {
    route: '/help/policies',
    title: 'Help: Policies',
    area: 'Help',
    source: 'Help article CMS + SEO',
    status: 'admin',
    adminPath: '/content/help-articles',
    notes: 'Managed through Help Articles.',
  },
  {
    route: '/help/pro',
    title: 'Help: Pro',
    area: 'Help',
    source: 'Help article CMS + SEO',
    status: 'admin',
    adminPath: '/content/help-articles',
    notes: 'Managed through Help Articles.',
  },
  {
    route: '/help/registration',
    title: 'Help: Registration',
    area: 'Help',
    source: 'Help article CMS + SEO',
    status: 'admin',
    adminPath: '/content/help-articles',
    notes: 'Managed through Help Articles.',
  },
  {
    route: '/help/trust-safety',
    title: 'Help: Trust & Safety',
    area: 'Help',
    source: 'Help article CMS + SEO',
    status: 'admin',
    adminPath: '/content/help-articles',
    notes: 'Managed through Help Articles.',
  },
  {
    route: '/account',
    title: 'Account',
    area: 'Account',
    source: 'Live account data',
    status: 'code',
    notes: 'Application page backed by account data, not CMS.',
  },
  {
    route: '/dashboard',
    title: 'Dashboard',
    area: 'Account',
    source: 'Live user dashboard',
    status: 'code',
    notes: 'Operational/account page, not content-managed.',
  },
  {
    route: '/my-tasks',
    title: 'My Tasks',
    area: 'Account',
    source: 'Live user task data',
    status: 'code',
    notes: 'Operational/account page, not content-managed.',
  },
  {
    route: '/referral',
    title: 'Referral',
    area: 'Referral',
    source: 'CMS page + referral flow',
    status: 'partial',
    adminPath: '/content/pages/referral',
    notes: 'Visible copy is page-managed. Referral logic and delivery still live in code.',
  },
  {
    route: '/for-business',
    title: 'For Business',
    area: 'Marketing',
    source: 'CMS Page + SEO',
    status: 'admin',
    adminPath: '/content/pages/for-business',
    notes: 'Public content is now managed in the page editor. Partnership form behavior remains in code.',
  },
  {
    route: '/partner',
    title: 'Partner',
    area: 'Marketing',
    source: 'Redirect alias',
    status: 'partial',
    adminPath: '/content/pages/for-business',
    notes: 'Alias route redirecting to /for-business.',
  },
  {
    route: '/become-tasker',
    title: 'Become Tasker',
    area: 'Marketing',
    source: 'Redirect alias',
    status: 'partial',
    adminPath: '/content/pages/become-100-handy-pro',
    notes: 'Alias route redirecting to /become-100-handy-pro.',
  },
  {
    route: '/become-100-handy-pro',
    title: 'Become 100 Handy Pro',
    area: 'Marketing',
    source: 'CMS Page + SEO',
    status: 'admin',
    adminPath: '/content/pages/become-100-handy-pro',
    notes: 'Public marketing content is now managed in the page editor.',
  },
  {
    route: '/press',
    title: 'Press',
    area: 'Marketing',
    source: 'CMS Page + SEO',
    status: 'admin',
    adminPath: '/content/pages/press',
    notes: 'Hero, media contacts, releases, resources, and story content are page-managed.',
  },
  {
    route: '/handycare',
    title: 'Handycare',
    area: 'Marketing',
    source: 'CMS Page + SEO',
    status: 'admin',
    adminPath: '/content/pages/handycare',
    notes: 'Current page content is fully managed in the page editor.',
  },
  {
    route: '/handyman-london',
    title: 'Handyman London',
    area: 'Marketing',
    source: 'CMS Page + SEO landing content',
    status: 'partial',
    adminPath: '/content/pages/handyman-london',
    notes: 'Main landing-page content is now page-managed. Decorative UI and some structural route behavior remain in code.',
  },
  {
    route: '/wallpapering-near-me',
    title: 'Wallpapering Near Me',
    area: 'Marketing',
    source: 'CMS Page + SEO landing content',
    status: 'partial',
    adminPath: '/content/pages/wallpapering-near-me',
    notes: 'Main landing-page content is now page-managed. Decorative UI and some structural route behavior remain in code.',
  },
  {
    route: '/landing-v2',
    title: 'Landing V2',
    area: 'Marketing',
    source: 'Code-managed experiment page',
    status: 'code',
    notes: 'Experimental page, not tied to CMS.',
  },
  {
    route: '/elite-taskers',
    title: 'Elite Taskers',
    area: 'Marketing',
    source: 'Legacy code-managed route',
    status: 'partial',
    adminPath: '/content/pages/elite-taskers',
    notes: 'Legacy route exists alongside the CMS-backed 100 Handy Star page.',
  },
]

export const webPageInventory: WebPageInventoryEntry[] = [...registryEntries, ...extraEntries].sort((a, b) =>
  a.route.localeCompare(b.route)
)
