insert into public.app_content (platform, screen_key, section_key, field_key, value, status)
values
  ('shared', 'auth_welcome', 'hero', 'title', 'Welcome', 'published'),
  ('shared', 'auth_welcome', 'footer', 'cta', 'Get started', 'published'),

  ('shared', 'auth_client_start', 'header', 'not_now', 'Not now', 'published'),
  ('shared', 'auth_client_start', 'hero', 'title', 'Welcome to 100Handy', 'published'),
  ('shared', 'auth_client_start', 'actions', 'create_account', 'Create Account', 'published'),
  ('shared', 'auth_client_start', 'actions', 'sign_in', 'Sign in', 'published'),
  ('shared', 'auth_client_start', 'legal', 'prefix', 'I agree to the', 'published'),
  ('shared', 'auth_client_start', 'legal', 'terms_label', 'Terms of Service', 'published'),
  ('shared', 'auth_client_start', 'legal', 'middle', 'and have reviewed the', 'published'),
  ('shared', 'auth_client_start', 'legal', 'privacy_label', 'Privacy Policy', 'published'),
  ('shared', 'auth_client_start', 'legal', 'suffix', '.', 'published'),
  ('shared', 'auth_client_start', 'links', 'offer_services', 'Looking to offer services on 100Handy', 'published'),

  ('shared', 'auth_professional_start', 'hero', 'title', 'Offer services on 100Handy', 'published'),
  ('shared', 'auth_professional_start', 'actions', 'create_account', 'Create Account', 'published'),
  ('shared', 'auth_professional_start', 'actions', 'sign_in', 'Sign in', 'published'),
  ('shared', 'auth_professional_start', 'legal', 'prefix', 'I agree to the', 'published'),
  ('shared', 'auth_professional_start', 'legal', 'terms_label', 'Terms of Service', 'published'),
  ('shared', 'auth_professional_start', 'legal', 'middle', 'and have reviewed the', 'published'),
  ('shared', 'auth_professional_start', 'legal', 'privacy_label', 'Privacy Policy', 'published'),
  ('shared', 'auth_professional_start', 'legal', 'suffix', '.', 'published'),

  ('shared', 'auth_sign_in', 'fields', 'email_placeholder', 'Email', 'published'),
  ('shared', 'auth_sign_in', 'fields', 'password_placeholder', 'Password', 'published'),
  ('shared', 'auth_sign_in', 'actions', 'submit', 'Log in', 'published'),
  ('shared', 'auth_sign_in', 'actions', 'submitting', 'Logging in...', 'published'),
  ('shared', 'auth_sign_in', 'links', 'forgot_prefix', 'Forgot your password?', 'published'),
  ('shared', 'auth_sign_in', 'links', 'forgot_cta', 'Reset it', 'published'),
  ('shared', 'auth_sign_in', 'oauth', 'divider', 'Or continue with', 'published'),
  ('shared', 'auth_sign_in', 'oauth', 'google_label', 'Google', 'published'),
  ('shared', 'auth_sign_in', 'oauth', 'google_loading', 'Connecting...', 'published'),
  ('shared', 'auth_sign_in', 'oauth', 'apple_label', 'Apple', 'published'),

  ('shared', 'auth_forgot_password', 'header', 'title', 'Reset Password', 'published'),
  ('shared', 'auth_forgot_password', 'body', 'description', 'Enter your email address and we''ll send you a verification code to reset your password.', 'published'),
  ('shared', 'auth_forgot_password', 'fields', 'email_placeholder', 'Email', 'published'),
  ('shared', 'auth_forgot_password', 'actions', 'submit', 'Send verification code', 'published'),
  ('shared', 'auth_forgot_password', 'actions', 'submitting', 'Sending...', 'published'),
  ('shared', 'auth_forgot_password', 'links', 'remember_prefix', 'Remember your password?', 'published'),
  ('shared', 'auth_forgot_password', 'links', 'remember_cta', 'Sign in', 'published'),
  ('shared', 'auth_forgot_password', 'feedback', 'success_title', 'Code sent!', 'published'),
  ('shared', 'auth_forgot_password', 'feedback', 'success_body', 'Check your email for the verification code', 'published'),
  ('shared', 'auth_forgot_password', 'feedback', 'error_title', 'Failed to send code', 'published'),
  ('shared', 'auth_forgot_password', 'feedback', 'error_body', 'Please try again', 'published'),

  ('shared', 'auth_client_onboarding', 'slide_1', 'description', E'Help with everyday\nLife at your fingertips.', 'published'),
  ('shared', 'auth_client_onboarding', 'slide_2', 'description', E'See reviews prices\nof 140,000+\nbackground\nchecked Taskers.', 'published'),
  ('shared', 'auth_client_onboarding', 'slide_3', 'description', E'Chat with your 100Handy Pro to schedule\nThe job and get it done.', 'published'),
  ('shared', 'auth_client_onboarding', 'slide_4', 'description', E'Manage your tasks and build your\nInner circle of taskers.', 'published'),
  ('shared', 'auth_client_onboarding', 'actions', 'skip', 'Skip', 'published'),
  ('shared', 'auth_client_onboarding', 'actions', 'next', 'Got it', 'published'),
  ('shared', 'auth_client_onboarding', 'actions', 'complete', 'Get started', 'published'),

  ('shared', 'client_support', 'header', 'title', 'Support', 'published'),
  ('shared', 'client_support', 'menu', 'message_support', 'Message Support', 'published'),
  ('shared', 'client_support', 'menu', 'view_tickets', 'View My Tickets', 'published'),
  ('shared', 'client_support', 'menu', 'support_center', 'Support Center', 'published'),
  ('shared', 'client_support', 'menu', 'support_center_url', 'https://100handy.com/support', 'published'),
  ('shared', 'client_support', 'menu', 'cancellation_policy', 'Cancellation Policy', 'published'),
  ('shared', 'client_support', 'policy', 'title', 'Cancellation Policy', 'published'),
  ('shared', 'client_support', 'policy', 'body', E'Free cancellation up to 24 hours before your booking start time.\n\nCancellations made less than 24 hours before the booking will incur a 50% cancellation fee.\n\nNo-shows will be charged the full booking amount.', 'published'),
  ('shared', 'client_support', 'menu', 'delete_account', 'Delete Account', 'published'),
  ('shared', 'client_support', 'delete', 'title', 'Delete Account', 'published'),
  ('shared', 'client_support', 'delete', 'warning', 'This action cannot be undone. All your data, bookings, and reviews will be permanently deleted.', 'published'),
  ('shared', 'client_support', 'delete', 'prompt', 'Enter your password to confirm.', 'published'),
  ('shared', 'client_support', 'delete', 'password_placeholder', 'Password', 'published'),
  ('shared', 'client_support', 'delete', 'confirm_cta', 'Delete My Account', 'published'),
  ('shared', 'client_support', 'delete', 'cancel_cta', 'Cancel', 'published'),
  ('shared', 'client_support', 'delete', 'success_title', 'Success', 'published'),
  ('shared', 'client_support', 'delete', 'success_body', 'Your account has been deleted', 'published'),
  ('shared', 'client_support', 'delete', 'error_title', 'Error', 'published'),
  ('shared', 'client_support', 'delete', 'wrong_password', 'Incorrect password. Please try again.', 'published'),
  ('shared', 'client_support', 'delete', 'generic_error', 'Failed to delete account. Please try again or contact support.', 'published'),
  ('shared', 'client_support', 'support_center', 'error_title', 'Error', 'published'),
  ('shared', 'client_support', 'support_center', 'error_body', 'Unable to open support center', 'published'),

  ('shared', 'client_support_chat', 'header', 'title', '100Handy Support', 'published'),
  ('shared', 'client_support_chat', 'header', 'subtitle', 'We''re here to help', 'published'),
  ('shared', 'client_support_chat', 'loading', 'creating_ticket', 'Creating support ticket...', 'published'),
  ('shared', 'client_support_chat', 'loading', 'generic', 'Loading...', 'published'),
  ('shared', 'client_support_chat', 'messages', 'empty', 'No messages yet. Start the conversation!', 'published'),
  ('shared', 'client_support_chat', 'input', 'active_placeholder', 'Type a message', 'published'),
  ('shared', 'client_support_chat', 'input', 'new_placeholder', 'Start a conversation with support', 'published'),
  ('shared', 'client_support_chat', 'errors', 'init_title', 'Error', 'published'),
  ('shared', 'client_support_chat', 'errors', 'init_body', 'Failed to load support chat. Please try again.', 'published'),
  ('shared', 'client_support_chat', 'errors', 'send_title', 'Error', 'published'),
  ('shared', 'client_support_chat', 'errors', 'send_prefix', 'Failed to send message:', 'published'),

  ('shared', 'client_support_tickets', 'header', 'title', 'My Tickets', 'published'),
  ('shared', 'client_support_tickets', 'actions', 'create', 'Create New Ticket', 'published'),
  ('shared', 'client_support_tickets', 'loading', 'text', 'Loading tickets...', 'published'),
  ('shared', 'client_support_tickets', 'empty', 'title', 'No Support Tickets', 'published'),
  ('shared', 'client_support_tickets', 'empty', 'body', 'You haven''t created any support tickets yet', 'published'),
  ('shared', 'client_support_tickets', 'sections', 'active_prefix', 'Active', 'published'),
  ('shared', 'client_support_tickets', 'sections', 'closed_prefix', 'Closed', 'published'),
  ('shared', 'client_support_tickets', 'delete', 'title', 'Delete Ticket', 'published'),
  ('shared', 'client_support_tickets', 'delete', 'body_template', 'Are you sure you want to delete "{subject}"? This action cannot be undone.', 'published'),
  ('shared', 'client_support_tickets', 'delete', 'cancel_cta', 'Cancel', 'published'),
  ('shared', 'client_support_tickets', 'delete', 'confirm_cta', 'Delete', 'published'),
  ('shared', 'client_support_tickets', 'delete', 'success_title', 'Success', 'published'),
  ('shared', 'client_support_tickets', 'delete', 'success_body', 'Ticket deleted successfully', 'published'),
  ('shared', 'client_support_tickets', 'delete', 'error_title', 'Error', 'published'),
  ('shared', 'client_support_tickets', 'delete', 'error_body', 'Failed to delete ticket. Please try again.', 'published'),

  ('shared', 'client_messages', 'header', 'title', 'Messages', 'published'),
  ('shared', 'client_messages', 'auth', 'title', 'Please sign in', 'published'),
  ('shared', 'client_messages', 'auth', 'body', 'You need to be signed in to view your messages.', 'published'),
  ('shared', 'client_messages', 'auth', 'cta', 'Sign In', 'published'),
  ('shared', 'client_messages', 'loading', 'text', 'Loading conversations...', 'published'),
  ('shared', 'client_messages', 'error', 'title', 'Unable to load messages', 'published'),
  ('shared', 'client_messages', 'error', 'body', 'Please check your connection and try again', 'published'),
  ('shared', 'client_messages', 'error', 'cta', 'Try Again', 'published'),
  ('shared', 'client_messages', 'empty', 'title', 'No messages yet', 'published'),
  ('shared', 'client_messages', 'empty', 'body', 'Start a conversation with your 100Handy Pro after booking', 'published'),

  ('shared', 'client_search_services', 'search', 'placeholder', 'Search for services...', 'published'),
  ('shared', 'client_search_services', 'loading', 'text', 'Loading categories...', 'published'),
  ('shared', 'client_search_services', 'error', 'title', 'Error loading categories', 'published'),
  ('shared', 'client_search_services', 'error', 'body', 'Please try again later', 'published'),
  ('shared', 'client_search_services', 'empty', 'title', 'No services found', 'published'),
  ('shared', 'client_search_services', 'empty', 'body', 'Try searching with different keywords', 'published')
on conflict (platform, screen_key, section_key, field_key) do nothing;
