insert into public.app_content (platform, screen_key, section_key, field_key, value, status)
values
  ('shared', 'client_profile', 'header', 'title', 'Profile', 'published'),
  ('shared', 'client_profile', 'auth', 'title', 'Please sign in', 'published'),
  ('shared', 'client_profile', 'auth', 'body', 'You need to be signed in to view your profile.', 'published'),
  ('shared', 'client_profile', 'auth', 'cta', 'Sign In', 'published'),
  ('shared', 'client_profile', 'loading', 'text', 'Loading profile...', 'published'),
  ('shared', 'client_profile', 'error', 'retry', 'Retry', 'published'),
  ('shared', 'client_profile', 'referral', 'cta', 'Help your friends, Get £10', 'published'),
  ('shared', 'client_profile', 'actions', 'offer_services', 'Offer services with 100Handy', 'published'),
  ('shared', 'client_profile', 'actions', 'logging_out', 'Error', 'published'),
  ('shared', 'client_profile', 'actions', 'logging_out_body', 'Failed to sign out. Please try again.', 'published'),
  ('shared', 'client_profile', 'actions', 'logout', 'Log out', 'published'),
  ('shared', 'client_profile', 'privacy', 'title', 'Privacy Notice', 'published'),
  ('shared', 'client_profile', 'privacy', 'body', 'By selecting "Accept All", you agree to the app storing information to enhance device navigation, analyze usage, and assist in our marketing efforts', 'published'),
  ('shared', 'client_profile', 'privacy', 'accept_cta', 'Accept All Cookies', 'published'),
  ('shared', 'client_profile', 'privacy', 'settings_cta', 'Cookies Settings', 'published'),
  ('shared', 'client_profile', 'verify', 'title', 'Verify Identity', 'published'),
  ('shared', 'client_profile', 'verify', 'body', 'Enter your password to access this section.', 'published'),
  ('shared', 'client_profile', 'verify', 'password_placeholder', 'Password', 'published'),
  ('shared', 'client_profile', 'verify', 'cta', 'Verify & Continue', 'published'),
  ('shared', 'client_profile', 'switch', 'error_title', 'Switch failed', 'published'),

  ('shared', 'client_notifications', 'header', 'title', 'Notifications', 'published'),
  ('shared', 'client_notifications', 'empty', 'title', 'No notifications yet', 'published'),
  ('shared', 'client_notifications', 'empty', 'body', 'You''ll see booking updates and messages here.', 'published'),

  ('shared', 'client_promotions', 'header', 'title', 'Promotions', 'published'),
  ('shared', 'client_promotions', 'card', 'title', 'Help Your Friends, Get £10', 'published'),
  ('shared', 'client_promotions', 'card', 'subtitle', 'Refer a Friend', 'published'),

  ('shared', 'professional_dashboard', 'header', 'greeting_prefix', 'Hello,', 'published'),
  ('shared', 'professional_dashboard', 'progress', 'label_prefix', 'Onboarding progress', 'published'),
  ('shared', 'professional_dashboard', 'progress', 'loading', 'Loading your progress...', 'published'),
  ('shared', 'professional_dashboard', 'tasks', 'verify_identity', 'Verify your identity', 'published'),
  ('shared', 'professional_dashboard', 'tasks', 'name_price', 'Name your price', 'published'),
  ('shared', 'professional_dashboard', 'tasks', 'direct_deposit', 'Set up direct deposit', 'published'),
  ('shared', 'professional_dashboard', 'tasks', 'profile_photo', 'Upload a profile photo', 'published'),
  ('shared', 'professional_dashboard', 'tasks', 'availability', 'Set availability', 'published'),
  ('shared', 'professional_dashboard', 'tasks', 'work_area', 'Set work area', 'published'),
  ('shared', 'professional_dashboard', 'alerts', 'verification_in_progress_title', 'Verification In Progress', 'published'),
  ('shared', 'professional_dashboard', 'alerts', 'verification_in_progress_body', 'Your identity verification is already being reviewed. Please wait.', 'published'),
  ('shared', 'professional_dashboard', 'alerts', 'verification_received_title', 'Verification received', 'published'),
  ('shared', 'professional_dashboard', 'alerts', 'verification_received_body', 'Stripe finished the verification flow. Your status will update after the backend confirms the result.', 'published'),
  ('shared', 'professional_dashboard', 'alerts', 'verification_failed_title', 'Verification Failed', 'published'),
  ('shared', 'professional_dashboard', 'alerts', 'verification_failed_body', 'Please try again.', 'published'),
  ('shared', 'professional_dashboard', 'alerts', 'verification_error_title', 'Error', 'published'),
  ('shared', 'professional_dashboard', 'alerts', 'verification_error_body', 'Failed to start verification. Please try again.', 'published'),
  ('shared', 'professional_dashboard', 'banner', 'verified_title', 'Account Verified', 'published'),
  ('shared', 'professional_dashboard', 'banner', 'verified_body', 'Your identity has been verified. You can now receive bookings.', 'published'),
  ('shared', 'professional_dashboard', 'banner', 'submitted_title', 'Verification In Progress', 'published'),
  ('shared', 'professional_dashboard', 'banner', 'submitted_body', 'Your identity verification is being reviewed. This usually takes a few minutes.', 'published'),
  ('shared', 'professional_dashboard', 'banner', 'rejected_title', 'Verification Failed', 'published'),
  ('shared', 'professional_dashboard', 'banner', 'rejected_body', 'Tap here to try again with clear photos of your ID.', 'published'),
  ('shared', 'professional_dashboard', 'banner', 'default_title', 'Your account isn''t live yet!', 'published'),
  ('shared', 'professional_dashboard', 'banner', 'default_body', 'Tap here to verify your identity and activate your account.', 'published'),
  ('shared', 'professional_dashboard', 'banner', 'starting', 'Starting verification...', 'published'),
  ('shared', 'professional_dashboard', 'misc', 'professional_fallback_name', 'Professional', 'published'),

  ('shared', 'professional_notifications', 'header', 'title', 'Notifications', 'published'),
  ('shared', 'professional_notifications', 'empty', 'title', 'No notifications yet', 'published'),
  ('shared', 'professional_notifications', 'empty', 'body', 'You''ll see job requests and messages here.', 'published')
on conflict (platform, screen_key, section_key, field_key) do nothing;
