insert into public.app_content (platform, screen_key, section_key, field_key, value, status)
values
  ('shared', 'professional_profile', 'header', 'title', 'Profile', 'published'),
  ('shared', 'professional_profile', 'photo', 'add', 'Add Photo', 'published'),
  ('shared', 'professional_profile', 'photo', 'change', 'Change Photo', 'published'),
  ('shared', 'professional_profile', 'photo', 'permission_title', 'Permission Required', 'published'),
  ('shared', 'professional_profile', 'photo', 'library_permission_body', 'Sorry, we need camera roll permissions to upload a photo.', 'published'),
  ('shared', 'professional_profile', 'photo', 'camera_permission_body', 'Sorry, we need camera permissions to take a photo.', 'published'),
  ('shared', 'professional_profile', 'photo', 'success_title', 'Success', 'published'),
  ('shared', 'professional_profile', 'photo', 'success_body', 'Profile photo updated successfully!', 'published'),
  ('shared', 'professional_profile', 'photo', 'error_title', 'Error', 'published'),
  ('shared', 'professional_profile', 'photo', 'error_body', 'Failed to upload photo. Please try again.', 'published'),
  ('shared', 'professional_profile', 'misc', 'fallback_name', 'Professional', 'published'),
  ('shared', 'professional_profile', 'menu', 'account_detail', 'Account detail', 'published'),
  ('shared', 'professional_profile', 'menu', 'pro_profile', 'Pro profile', 'published'),
  ('shared', 'professional_profile', 'menu', 'performance', 'Performance', 'published'),
  ('shared', 'professional_profile', 'menu', 'sync_calendar', 'Sync calendar', 'published'),
  ('shared', 'professional_profile', 'menu', 'chat_templates', 'Chat templates', 'published'),
  ('shared', 'professional_profile', 'menu', 'promote_yourself', 'Promote yourself', 'published'),
  ('shared', 'professional_profile', 'menu', 'payments', 'Payments', 'published'),
  ('shared', 'professional_profile', 'menu', 'notifications', 'Notifications', 'published'),
  ('shared', 'professional_profile', 'menu', 'support', 'Support', 'published'),
  ('shared', 'professional_profile', 'menu', 'account_security', 'Account security', 'published'),
  ('shared', 'professional_profile', 'menu', 'about', 'About', 'published'),
  ('shared', 'professional_profile', 'menu', 'password', 'Password', 'published'),
  ('shared', 'professional_profile', 'menu', 'switch_to_client', 'Go 100Handy', 'published'),
  ('shared', 'professional_profile', 'menu', 'logout', 'Log out', 'published'),
  ('shared', 'professional_profile', 'switch', 'error_title', 'Switch failed', 'published'),
  ('shared', 'professional_profile', 'switch', 'error_body', 'Could not switch to client mode. Please try again.', 'published'),
  ('shared', 'professional_profile', 'switch', 'generic_error_body', 'An error occurred while switching roles. Please try again.', 'published'),

  ('shared', 'professional_support', 'header', 'title', 'Support', 'published'),
  ('shared', 'professional_support', 'menu', 'support_center', '100Handy Support', 'published'),
  ('shared', 'professional_support', 'menu', 'support_center_url', 'https://100handy.com/help', 'published'),
  ('shared', 'professional_support', 'menu', 'test_notifications', 'Test push notifications', 'published'),
  ('shared', 'professional_support', 'notifications', 'disabled_title', 'Notifications disabled', 'published'),
  ('shared', 'professional_support', 'notifications', 'disabled_body', 'Enable notifications to test this feature.', 'published'),
  ('shared', 'professional_support', 'notifications', 'sent_title', 'Test notification sent', 'published'),
  ('shared', 'professional_support', 'notifications', 'sent_body', 'A banner should appear immediately.', 'published'),
  ('shared', 'professional_support', 'notifications', 'error_title', 'Notification test failed', 'published'),
  ('shared', 'professional_support', 'notifications', 'error_body', 'Unable to trigger the test notification.', 'published'),
  ('shared', 'professional_support', 'version', 'prefix', 'Version', 'published'),

  ('shared', 'professional_add_profile_photo', 'header', 'title', 'Add profile photo', 'published'),
  ('shared', 'professional_add_profile_photo', 'hero', 'title', 'Show off your best self!', 'published'),
  ('shared', 'professional_add_profile_photo', 'tips', 'intro', 'A great photo increases your chances of being hired. Some tips:', 'published'),
  ('shared', 'professional_add_profile_photo', 'tips', 'item_1', 'Center yourself and smile at the camera', 'published'),
  ('shared', 'professional_add_profile_photo', 'tips', 'item_2', 'Take a headshot - from the chest up.', 'published'),
  ('shared', 'professional_add_profile_photo', 'tips', 'item_3', 'Make sure it''s focused and well-lit.', 'published'),
  ('shared', 'professional_add_profile_photo', 'actions', 'add_photo', 'Add Photo', 'published'),
  ('shared', 'professional_add_profile_photo', 'sheet', 'title', 'Select a Photo', 'published'),
  ('shared', 'professional_add_profile_photo', 'sheet', 'library', 'Library', 'published'),
  ('shared', 'professional_add_profile_photo', 'sheet', 'camera', 'Take a photo', 'published'),
  ('shared', 'professional_add_profile_photo', 'alerts', 'permission_title', 'Permission Required', 'published'),
  ('shared', 'professional_add_profile_photo', 'alerts', 'library_permission_body', 'Sorry, we need camera roll permissions to upload a photo.', 'published'),
  ('shared', 'professional_add_profile_photo', 'alerts', 'camera_permission_body', 'Sorry, we need camera permissions to take a photo.', 'published'),
  ('shared', 'professional_add_profile_photo', 'alerts', 'success_title', 'Success', 'published'),
  ('shared', 'professional_add_profile_photo', 'alerts', 'success_body', 'Profile photo updated successfully!', 'published'),
  ('shared', 'professional_add_profile_photo', 'alerts', 'error_title', 'Error', 'published'),
  ('shared', 'professional_add_profile_photo', 'alerts', 'error_body', 'Failed to upload photo. Please try again.', 'published'),

  ('shared', 'professional_set_availability', 'header', 'title', 'Set Availability', 'published'),
  ('shared', 'professional_set_availability', 'loading', 'text', 'Loading availability...', 'published'),
  ('shared', 'professional_set_availability', 'slot', 'available', 'Available', 'published'),
  ('shared', 'professional_set_availability', 'slot', 'repeats_weekly', 'Repeats weekly', 'published'),
  ('shared', 'professional_set_availability', 'slot', 'one_time', 'One-time', 'published'),
  ('shared', 'professional_set_availability', 'preview', 'merging', 'Merging...', 'published'),
  ('shared', 'professional_set_availability', 'preview', 'new_slot', 'New Slot', 'published'),
  ('shared', 'professional_set_availability', 'modal', 'title', 'Add Availability', 'published'),
  ('shared', 'professional_set_availability', 'modal', 'to', 'to', 'published'),
  ('shared', 'professional_set_availability', 'repeat', 'title', 'Repeat weekly', 'published'),
  ('shared', 'professional_set_availability', 'repeat', 'enabled_body', 'This availability will repeat every week on the selected days.', 'published'),
  ('shared', 'professional_set_availability', 'repeat', 'disabled_body', 'This availability will only be added for this date.', 'published'),
  ('shared', 'professional_set_availability', 'actions', 'saving', 'Saving...', 'published'),
  ('shared', 'professional_set_availability', 'actions', 'merge', 'Merge availability', 'published'),
  ('shared', 'professional_set_availability', 'actions', 'add', 'Add Availability', 'published'),
  ('shared', 'professional_set_availability', 'actions', 'discard', 'Discard', 'published'),
  ('shared', 'professional_set_availability', 'errors', 'invalid_time_title', 'Invalid time', 'published'),
  ('shared', 'professional_set_availability', 'errors', 'invalid_time_body', 'End time must be after start time', 'published'),
  ('shared', 'professional_set_availability', 'errors', 'missing_days_title', 'Missing weekdays', 'published'),
  ('shared', 'professional_set_availability', 'errors', 'missing_days_body', 'Select at least one weekday', 'published'),
  ('shared', 'professional_set_availability', 'toasts', 'saved_title', 'Saved', 'published'),
  ('shared', 'professional_set_availability', 'toasts', 'saved_body', 'Availability updated', 'published'),
  ('shared', 'professional_set_availability', 'toasts', 'save_failed_title', 'Save failed', 'published'),
  ('shared', 'professional_set_availability', 'toasts', 'retry_body', 'Please try again', 'published'),
  ('shared', 'professional_set_availability', 'toasts', 'resize_failed_title', 'Resize failed', 'published'),

  ('shared', 'professional_set_work_area', 'loading', 'text', 'Loading...', 'published'),
  ('shared', 'professional_set_work_area', 'review', 'title', 'Reviewing work area', 'published'),
  ('shared', 'professional_set_work_area', 'actions', 'drawing', 'Draw on map', 'published'),
  ('shared', 'professional_set_work_area', 'actions', 'draw', 'Draw area', 'published'),
  ('shared', 'professional_set_work_area', 'actions', 'clear', 'Clear', 'published'),
  ('shared', 'professional_set_work_area', 'actions', 'save', 'Save work area', 'published'),
  ('shared', 'professional_set_work_area', 'toasts', 'saved_title', 'Saved', 'published'),
  ('shared', 'professional_set_work_area', 'toasts', 'saved_body', 'Work area updated', 'published'),
  ('shared', 'professional_set_work_area', 'toasts', 'save_failed_title', 'Save failed', 'published'),
  ('shared', 'professional_set_work_area', 'toasts', 'retry_body', 'Please try again', 'published')
on conflict (platform, screen_key, section_key, field_key) do nothing;
