with seeded as (
  select *
  from (
    values
      ('loc_pa_ab', 'AB postcode area', 'ab', 'loc_sco'),
      ('loc_pa_al', 'AL postcode area', 'al', 'loc_eng'),
      ('loc_pa_b', 'B postcode area', 'b', 'loc_eng'),
      ('loc_pa_ba', 'BA postcode area', 'ba', 'loc_eng'),
      ('loc_pa_bb', 'BB postcode area', 'bb', 'loc_eng'),
      ('loc_pa_bd', 'BD postcode area', 'bd', 'loc_eng'),
      ('loc_pa_bh', 'BH postcode area', 'bh', 'loc_eng'),
      ('loc_pa_bl', 'BL postcode area', 'bl', 'loc_eng'),
      ('loc_pa_bn', 'BN postcode area', 'bn', 'loc_eng'),
      ('loc_pa_br', 'BR postcode area', 'br', 'loc_london_region'),
      ('loc_pa_bs', 'BS postcode area', 'bs', 'loc_eng'),
      ('loc_pa_bt', 'BT postcode area', 'bt', 'loc_ni'),
      ('loc_pa_ca', 'CA postcode area', 'ca', 'loc_eng'),
      ('loc_pa_cb', 'CB postcode area', 'cb', 'loc_eng'),
      ('loc_pa_cf', 'CF postcode area', 'cf', 'loc_wal'),
      ('loc_pa_ch', 'CH postcode area', 'ch', 'loc_eng'),
      ('loc_pa_cm', 'CM postcode area', 'cm', 'loc_eng'),
      ('loc_pa_co', 'CO postcode area', 'co', 'loc_eng'),
      ('loc_pa_cr', 'CR postcode area', 'cr', 'loc_london_region'),
      ('loc_pa_ct', 'CT postcode area', 'ct', 'loc_eng'),
      ('loc_pa_cv', 'CV postcode area', 'cv', 'loc_eng'),
      ('loc_pa_cw', 'CW postcode area', 'cw', 'loc_eng'),
      ('loc_pa_da', 'DA postcode area', 'da', 'loc_london_region'),
      ('loc_pa_dd', 'DD postcode area', 'dd', 'loc_sco'),
      ('loc_pa_de', 'DE postcode area', 'de', 'loc_eng'),
      ('loc_pa_dg', 'DG postcode area', 'dg', 'loc_sco'),
      ('loc_pa_dh', 'DH postcode area', 'dh', 'loc_eng'),
      ('loc_pa_dl', 'DL postcode area', 'dl', 'loc_eng'),
      ('loc_pa_dn', 'DN postcode area', 'dn', 'loc_eng'),
      ('loc_pa_dt', 'DT postcode area', 'dt', 'loc_eng'),
      ('loc_pa_dy', 'DY postcode area', 'dy', 'loc_eng'),
      ('loc_pa_e', 'E postcode area', 'e', 'loc_london_region'),
      ('loc_pa_ec', 'EC postcode area', 'ec', 'loc_london_region'),
      ('loc_pa_eh', 'EH postcode area', 'eh', 'loc_sco'),
      ('loc_pa_en', 'EN postcode area', 'en', 'loc_london_region'),
      ('loc_pa_ex', 'EX postcode area', 'ex', 'loc_eng'),
      ('loc_pa_fk', 'FK postcode area', 'fk', 'loc_sco'),
      ('loc_pa_fy', 'FY postcode area', 'fy', 'loc_eng'),
      ('loc_pa_g', 'G postcode area', 'g', 'loc_sco'),
      ('loc_pa_gl', 'GL postcode area', 'gl', 'loc_eng'),
      ('loc_pa_gu', 'GU postcode area', 'gu', 'loc_eng'),
      ('loc_pa_ha', 'HA postcode area', 'ha', 'loc_london_region'),
      ('loc_pa_hd', 'HD postcode area', 'hd', 'loc_eng'),
      ('loc_pa_hg', 'HG postcode area', 'hg', 'loc_eng'),
      ('loc_pa_hp', 'HP postcode area', 'hp', 'loc_eng'),
      ('loc_pa_hr', 'HR postcode area', 'hr', 'loc_eng'),
      ('loc_pa_hs', 'HS postcode area', 'hs', 'loc_sco'),
      ('loc_pa_hu', 'HU postcode area', 'hu', 'loc_eng'),
      ('loc_pa_hx', 'HX postcode area', 'hx', 'loc_eng'),
      ('loc_pa_ig', 'IG postcode area', 'ig', 'loc_london_region'),
      ('loc_pa_ip', 'IP postcode area', 'ip', 'loc_eng'),
      ('loc_pa_iv', 'IV postcode area', 'iv', 'loc_sco'),
      ('loc_pa_ka', 'KA postcode area', 'ka', 'loc_sco'),
      ('loc_pa_kt', 'KT postcode area', 'kt', 'loc_london_region'),
      ('loc_pa_kw', 'KW postcode area', 'kw', 'loc_sco'),
      ('loc_pa_ky', 'KY postcode area', 'ky', 'loc_sco'),
      ('loc_pa_l', 'L postcode area', 'l', 'loc_eng'),
      ('loc_pa_la', 'LA postcode area', 'la', 'loc_eng'),
      ('loc_pa_ld', 'LD postcode area', 'ld', 'loc_wal'),
      ('loc_pa_le', 'LE postcode area', 'le', 'loc_eng'),
      ('loc_pa_ll', 'LL postcode area', 'll', 'loc_wal'),
      ('loc_pa_ln', 'LN postcode area', 'ln', 'loc_eng'),
      ('loc_pa_ls', 'LS postcode area', 'ls', 'loc_eng'),
      ('loc_pa_lu', 'LU postcode area', 'lu', 'loc_eng'),
      ('loc_pa_m', 'M postcode area', 'm', 'loc_eng'),
      ('loc_pa_me', 'ME postcode area', 'me', 'loc_eng'),
      ('loc_pa_mk', 'MK postcode area', 'mk', 'loc_eng'),
      ('loc_pa_ml', 'ML postcode area', 'ml', 'loc_sco'),
      ('loc_pa_n', 'N postcode area', 'n', 'loc_london_region'),
      ('loc_pa_ne', 'NE postcode area', 'ne', 'loc_eng'),
      ('loc_pa_ng', 'NG postcode area', 'ng', 'loc_eng'),
      ('loc_pa_nn', 'NN postcode area', 'nn', 'loc_eng'),
      ('loc_pa_np', 'NP postcode area', 'np', 'loc_wal'),
      ('loc_pa_nr', 'NR postcode area', 'nr', 'loc_eng'),
      ('loc_pa_nw', 'NW postcode area', 'nw', 'loc_london_region'),
      ('loc_pa_ol', 'OL postcode area', 'ol', 'loc_eng'),
      ('loc_pa_ox', 'OX postcode area', 'ox', 'loc_eng'),
      ('loc_pa_pa', 'PA postcode area', 'pa', 'loc_sco'),
      ('loc_pa_pe', 'PE postcode area', 'pe', 'loc_eng'),
      ('loc_pa_ph', 'PH postcode area', 'ph', 'loc_sco'),
      ('loc_pa_pl', 'PL postcode area', 'pl', 'loc_eng'),
      ('loc_pa_po', 'PO postcode area', 'po', 'loc_eng'),
      ('loc_pa_pr', 'PR postcode area', 'pr', 'loc_eng'),
      ('loc_pa_rg', 'RG postcode area', 'rg', 'loc_eng'),
      ('loc_pa_rh', 'RH postcode area', 'rh', 'loc_eng'),
      ('loc_pa_rm', 'RM postcode area', 'rm', 'loc_london_region'),
      ('loc_pa_s', 'S postcode area', 's', 'loc_eng'),
      ('loc_pa_sa', 'SA postcode area', 'sa', 'loc_wal'),
      ('loc_pa_se', 'SE postcode area', 'se', 'loc_london_region'),
      ('loc_pa_sg', 'SG postcode area', 'sg', 'loc_eng'),
      ('loc_pa_sk', 'SK postcode area', 'sk', 'loc_eng'),
      ('loc_pa_sl', 'SL postcode area', 'sl', 'loc_eng'),
      ('loc_pa_sm', 'SM postcode area', 'sm', 'loc_london_region'),
      ('loc_pa_sn', 'SN postcode area', 'sn', 'loc_eng'),
      ('loc_pa_so', 'SO postcode area', 'so', 'loc_eng'),
      ('loc_pa_sp', 'SP postcode area', 'sp', 'loc_eng'),
      ('loc_pa_sr', 'SR postcode area', 'sr', 'loc_eng'),
      ('loc_pa_ss', 'SS postcode area', 'ss', 'loc_eng'),
      ('loc_pa_st', 'ST postcode area', 'st', 'loc_eng'),
      ('loc_pa_sw', 'SW postcode area', 'sw', 'loc_london_region'),
      ('loc_pa_sy', 'SY postcode area', 'sy', 'loc_wal'),
      ('loc_pa_ta', 'TA postcode area', 'ta', 'loc_eng'),
      ('loc_pa_td', 'TD postcode area', 'td', 'loc_sco'),
      ('loc_pa_tf', 'TF postcode area', 'tf', 'loc_eng'),
      ('loc_pa_tn', 'TN postcode area', 'tn', 'loc_eng'),
      ('loc_pa_tq', 'TQ postcode area', 'tq', 'loc_eng'),
      ('loc_pa_tr', 'TR postcode area', 'tr', 'loc_eng'),
      ('loc_pa_ts', 'TS postcode area', 'ts', 'loc_eng'),
      ('loc_pa_tw', 'TW postcode area', 'tw', 'loc_london_region'),
      ('loc_pa_ub', 'UB postcode area', 'ub', 'loc_london_region'),
      ('loc_pa_w', 'W postcode area', 'w', 'loc_london_region'),
      ('loc_pa_wa', 'WA postcode area', 'wa', 'loc_eng'),
      ('loc_pa_wc', 'WC postcode area', 'wc', 'loc_london_region'),
      ('loc_pa_wd', 'WD postcode area', 'wd', 'loc_london_region'),
      ('loc_pa_wf', 'WF postcode area', 'wf', 'loc_eng'),
      ('loc_pa_wn', 'WN postcode area', 'wn', 'loc_eng'),
      ('loc_pa_wr', 'WR postcode area', 'wr', 'loc_eng'),
      ('loc_pa_ws', 'WS postcode area', 'ws', 'loc_eng'),
      ('loc_pa_wv', 'WV postcode area', 'wv', 'loc_eng'),
      ('loc_pa_yo', 'YO postcode area', 'yo', 'loc_eng'),
      ('loc_pa_ze', 'ZE postcode area', 'ze', 'loc_sco')
  ) as rows(id, name, slug, parent_id)
)
insert into public.location_areas (
  id,
  name,
  slug,
  area_type,
  parent_id,
  country_code,
  enabled,
  sort_order,
  notes
)
select
  id,
  name,
  slug,
  'postcode_area',
  parent_id,
  'GB',
  true,
  0,
  'Seeded UK postcode area'
from seeded
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  parent_id = excluded.parent_id,
  enabled = excluded.enabled,
  notes = excluded.notes;
